[holbuild]
minimum_version = "0.11.3"

[project]
name = "vyper-hol"
version = "0.2.3"

[build]
roots = ["vyperHolScript.sml",
         "semantics/vyperCheckContractLibTestScript.sml",
         "frontend/vyperCheckContractFrontendLibTestScript.sml",
         "tests/vyperCheckContractTraceLibTestScript.sml"]

[build.theory_tactic_timeouts]
"semantics/vyperInterpreterScript.sml" = 5
"semantics/prop/vyperLogPreservationScript.sml" = 5
"venom/defs/venomExecSemanticsScript.sml" = 5
"venom/proofs/execEquivProofsScript.sml" = 5

[dependencies.verifereum]
git = "https://github.com/verifereum/verifereum.git"
rev = "b116b3c46c17381e968d25b81cd81b6ab2b76ab2"
