[holbuild]
schema = 2

[project]
name = "vyper-hol"
version = "0.1.1"

[build]
roots = ["vyperHolScript.sml"]

[dependencies.verifereum]
git = "https://github.com/verifereum/verifereum.git"
rev = "5cacc6adc7753b49f562db26da26a447472ad984"
