[holbuild]
minimum_version = "0.10.2"

[project]
name = "vyper-hol"
version = "0.2.3"

[build]
roots = ["vyperHolScript.sml"]

[dependencies.verifereum]
git = "https://github.com/verifereum/verifereum.git"
rev = "188bd6dc8286c8571823af1b44b6fd2935b3fcf1"
