[holbuild]
schema = 1

[project]
name = "verifereum"
version = "0.1.0"

[build]
members = [
  "verifereumScript.sml",
  "util",
  "spec",
  "spec/prop",
  "prog",
  "examples",
  "tests/vfmTestRunScript.sml",
  "tests/vfmTestAuxLib.sig",
  "tests/vfmTestAuxLib.sml",
  "tests/vfmTestDefLib.sig",
  "tests/vfmTestDefLib.sml",
  "tests/vfmTestResultLib.sig",
  "tests/vfmTestResultLib.sml",
]
roots = ["verifereumScript.sml"]

[dependencies.HOLDIR]
manifest = "holdir.manifest.toml"

[actions.wrappedEtherTheory]
loads = ["finite_mapSyntax"]
