name: 'Holmake Verifereum'
description: 'Builds/restores Verifereum Holmake outputs'

inputs:
  polyml-rev:
    required: true
    description: 'Resolved Poly/ML revision'
  hol4-rev:
    required: true
    description: 'Resolved HOL4 revision'
  verifereum-rev:
    required: true
    description: 'Resolved Verifereum revision'

runs:
  using: 'composite'
  steps:
    - name: Cache Verifereum build
      uses: actions/cache@v4
      id: cache-verifereum-build
      with:
        path: ~/verifereum/**/.hol
        key: verifereum-holmake-${{ runner.os }}-${{ inputs.polyml-rev }}-${{ inputs.hol4-rev }}-${{ inputs.verifereum-rev }}

    - name: Build Verifereum with Holmake
      if: steps.cache-verifereum-build.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd "$HOME/verifereum"
        Holmake
