Theory vyperTestDefs_functional_codegen_calling_convention_test_new_call_convention[no_sig_docs]
Ancestors jsonToVyper
Libs vyperTestLib
val () = make_definitions_for_file ("functional_codegen_calling_convention_test_new_call_convention", "vyper-test-exports/functional/codegen/calling_convention/test_new_call_convention.json");
