Theory vyperTest_functional_codegen_features_test_constructor[no_sig_docs]
Ancestors vyperTestDefs_functional_codegen_features_test_constructor
Libs vyperTestRunnerLib
val () = List.app run_test_on_traces $ all_traces "vyperTestDefs_functional_codegen_features_test_constructor";
