Theory vyperTest_functional_codegen_test_interfaces[no_sig_docs]
Ancestors vyperTestDefs_functional_codegen_test_interfaces
Libs vyperTestRunnerLib
val () = List.app run_test_on_traces $ all_traces "vyperTestDefs_functional_codegen_test_interfaces";
