Theory vyperTest_functional_codegen_types_numbers_test_signed_ints[no_sig_docs]
Ancestors vyperTestDefs_functional_codegen_types_numbers_test_signed_ints
Libs vyperTestRunnerLib
val () = List.app run_test_on_traces $ all_traces "vyperTestDefs_functional_codegen_types_numbers_test_signed_ints";
