Theory vyperTest_functional_codegen_types_test_identifier_naming[no_sig_docs]
Ancestors vyperTestDefs_functional_codegen_types_test_identifier_naming
Libs vyperTestRunnerLib
val () = List.app run_test_on_traces $ all_traces "vyperTestDefs_functional_codegen_types_test_identifier_naming";
