Theory vyperTest_functional_codegen_calling_convention_test_internal_call[no_sig_docs]
Ancestors vyperTestDefs_functional_codegen_calling_convention_test_internal_call
Libs vyperTestRunnerLib
val () = List.app run_test_on_traces $ all_traces "vyperTestDefs_functional_codegen_calling_convention_test_internal_call";
